export const genres = [
  "pop",
  "rock",
  "hip hop",
  "rap",
  "country",
  "classical",
  "jazz",
  "blues",
  "r&b",
  "soul",
  "funk",
  "disco",
  "reggae",
  "electronic",
  "edm",
  "house",
  "techno",
  "dubstep",
  "trap",
  "alternative rock",
  "indie rock",
  "folk",
  "punk",
  "heavy metal",
  "hard rock",
  "progressive rock",
  "progressive metal",
  "classic rock",
  "psychedelic rock",
  "soft rock",
  "pop rock",
  "grunge",
  "emo",
  "ska",
  "new wave",
  "synth-pop",
  "latin pop",
  "k-pop",
  "j-pop",
  "c-pop",
  "dancehall",
  "reggaeton",
  "afrobeats",
  "afrobeat",
  "gospel",
  "christian rock",
  "opera",
  "broadway",
  "bluegrass",
  "americana",
  "alt-country",
  "electro-pop",
  "singer-songwriter",
  "lo-fi",
  "ambient",
  "chillwave",
  "vaporwave",
  "industrial",
  "drum and bass",
  "breakbeat",
  "trance",
  "garage",
  "future bass",
  "deep house",
  "tropical house",
  "melodic techno",
  "big room",
  "moombahton",
  "psytrance",
  "hardstyle",
  "hardcore techno",
  "uk garage",
  "two-step",
  "dub",
  "roots reggae",
  "soca",
  "calypso",
  "bossa nova",
  "samba",
  "tango",
  "flamenco",
  "ranchera",
  "mariachi",
  "norteño",
  "corridos",
  "bachata",
  "merengue",
  "salsa",
  "cumbia",
  "bolero",
  "klezmer",
  "world music",
  "traditional folk",
  "celtic",
  "irish folk",
  "scottish folk",
  "greek folk",
  "turkish folk",
  "arabic pop",
  "rai",
  "moroccan gnawa",
  "african blues",
  "highlife",
  "mbaqanga",
  "kwaito",
  "gqom",
  "makossa",
  "azonto",
  "zouglou",
  "soukous",
  "tarab",
  "hindustani classical",
  "carnatic classical",
  "bollywood",
  "bhangra",
  "ghazal",
  "qawwali",
  "kirtan",
  "japanese enka",
  "anime music",
  "visual kei",
  "city pop",
  "chinese opera",
  "mongolian throat singing",
  "tuvan throat singing",
  "indigenous music",
  "native american music",
  "polka",
  "balkan brass",
  "balkan beats",
  "gypsy jazz",
  "roma music",
  "ethio-jazz",
  "desert blues",
  "tuareg music",
  "persian classical",
  "sufi music",
  "avant-garde jazz",
  "free jazz",
  "bebop",
  "hard bop",
  "swing",
  "big band",
  "baroque",
  "renaissance",
  "romantic classical",
  "neoclassical",
  "minimalism",
  "experimental",
  "art rock",
  "avant-garde",
  "shoegaze",
  "dream pop",
  "noise rock",
  "post-punk",
  "post-rock",
  "math rock",
  "sludge metal",
  "doom metal",
  "death metal",
  "black metal",
  "speed metal",
  "thrash metal",
  "metalcore",
  "deathcore",
  "grindcore",
  "melodic death metal",
  "symphonic metal",
  "folk metal",
  "viking metal",
  "power metal",
  "gothic metal",
  "nu-metal",
  "industrial metal",
  "jazz fusion",
  "latin jazz",
  "smooth jazz",
  "cool jazz",
  "acid jazz",
  "funk rock",
  "funk metal",
  "ska punk",
  "reggae rock",
  "pop punk",
  "skate punk",
  "horror punk",
  "psychobilly",
  "rockabilly",
  "surf rock",
  "garage rock",
  "post-grunge",
  "britpop",
  "mod revival",
  "yacht rock",
  "chillout",
  "downtempo",
  "future garage",
  "trip-hop",
  "idm",
  "glitch",
  "microhouse",
  "electro swing",
  "neo-soul",
  "boogie",
  "freestyle",
  "italo disco",
  "eurodance",
  "hyperpop",
  "drill",
  "cloud rap",
  "mumble rap",
  "conscious hip hop",
  "boom bap",
  "trap metal",
  "phonk",
];
