export const musician_roles = {
  Strings: [
    "Guitar",
    "Violin",
    "Bass",
    "Cello",
    "Harp",
    "Mandolin",
    "Ukulele",
    "Banjo",
    "Sitar",
  ],
  Keyboards: ["Piano", "Organ", "Keyboard", "Harpsichord"],
  Wind: [
    "Flute",
    "Clarinet",
    "Saxophone",
    "Oboe",
    "Bassoon",
    "Trumpet",
    "Trombone",
    "Horn",
    "Tuba",
    "Recorder",
  ],
  Percussion: ["Drums", "Timpani", "Xylophone", "Marimba", "Percussion"],
  Vocals: [
    "Lead Vocal",
    "Backing Vocal",
    "Soprano",
    "Alto",
    "Tenor",
    "Baritone",
    "Bass",
    "Choir",
    "Opera Singer",
  ],
  Other: ["Accordion", "Harmonica", "Bagpipes", "Lute", "Fiddle"],
};
