export const musician_roles = {
  string_instruments: [
    "Guitar",
    "Violin",
    "Bass",
    "Cello",
    "Harp",
    "Mandolin",
    "Ukulele",
    "Banjo",
    "Sitar",
  ],
  keyboard_instruments: ["Piano", "Organ", "Keyboard", "Harpsichord"],
  wind_instruments: [
    "Flute",
    "Clarinet",
    "Saxophone",
    "Oboe",
    "Bassoon",
    "Trumpet",
    "Trombone",
    "Horn",
    "Tuba",
    "Recorder",
  ],
  percussion_instruments: [
    "Drums",
    "Timpani",
    "Xylophone",
    "Marimba",
    "Percussion",
  ],
  vocals: [
    "Lead Vocal",
    "Backing Vocal",
    "Soprano",
    "Alto",
    "Tenor",
    "Baritone",
    "Bass",
    "Choir",
    "Opera Singer",
  ],
  other_instruments: ["Accordion", "Harmonica", "Bagpipes", "Lute", "Fiddle"],
};
